"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"           <head>\n"
"           <meta charset=\"UTF-8\">\n"
"                         <title>display page</title>\n"
"<link rel=\"stylesheet\" href=\"css/style.css\">\n"
"                            </head>\n"
"<body>\n"